pipeline {
    agent any
    environment {
        IMAGE_NAME = "pranavhude/myapp"
        TAG        = "latest"
    }

    stages {
        stage('Checkout Code') {
            steps {
                Checkout scm
            }
        }

        stage(Build Docker Image) {
            steps {
                sh '''
                docker build -t $IMAGE_NAME:$TAG .
                '''
            }
        }
        
        stage('Login & Push Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token' , variable: 'DOCKER_TOKEN')]) {
                    sh '''
                    echo $DOCKER_TOKEN | docker login -u pranavhude --password-stdin
                    docker push $IMAGE_NAME:$TAG
                    '''

                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh '''
                kubectl apply -f k8s/deployment.yaml
                kubectl apply -f k8s/service.yaml
                '''
            }
        }

    }
    post {
        success {
            echo "Application deployed successfully to EKS"
        }
        failure {
            echo "Deployment failed"
    
        }
    }
}